-- Migrates categories, stores, products, orders, order_items,
-- platform_settings and store_categories from bigint primary keys to the
-- uuid v7 generated by public.uuid_generate_v7() (see
-- 001_uuid_v7_function.sql, which must run first). product_views and
-- product_reviews already have uuid primary keys and are not re-keyed --
-- they only have their FK to products repointed at the new uuid.
--
-- Also adds stores.user_id (uuid, references auth.users), closing the gap
-- where seller authorization is resolved by parsing the login email's
-- local part against stores.phone. Section F's backfill uses that same
-- heuristic one last time, to interpret history; after this migration it
-- never authorizes anything again.
--
-- legacy_id / legacy_*_id columns are kept deliberately -- not referenced
-- by anything, but they make rollback a key swap rather than a restore,
-- and 44 ad-hoc scripts at backend/ root still assume integer ids.
--
-- One transaction: any failure anywhere rolls back everything.
begin;

-- ---------------------------------------------------------------
-- 0. Pre-flight: refuse to run if something outside this migration's
--    awareness depends on the nine tables in a way this migration would
--    silently break: a dependent view/matview, a foreign key reaching in
--    from a tenth table, an RLS policy on one of the nine, a unique
--    constraint/index sitting on a column section D renames, or a trigger
--    on one of the nine. Each of
--    these commits cleanly with no engine-level error if left unchecked --
--    silent damage, not a crash -- so they're checked here, loudly,
--    before a single column is touched.
--
--    The nine-table inventory this file works from was confirmed against
--    PostgREST's OpenAPI listing, which is weaker than it looks:
--    PostgREST omits relations with no grants to anon/authenticated, so
--    an ungranted table or view would never have appeared there. This
--    block checks the actual catalog instead of trusting that listing.
--    (RLS is provably inert in this system today -- none of the three
--    frontends carries @supabase/supabase-js, they all go through the
--    Express API, and backend/src/config/supabase.js uses the service
--    role key, which bypasses RLS -- but this migration cannot see
--    whether a policy exists on production, and if one does, section D's
--    renames corrupt it permanently and silently.)
--
--    This section also SNAPSHOTS every foreign key on the nine tables
--    before section C drops them, so section E can put back exactly what
--    was there rather than a hardcoded guess -- see the snapshot's own
--    comment below.
-- ---------------------------------------------------------------

-- Snapshot of the nine tables' foreign keys, taken before anything is
-- dropped. Section C discovers and drops every fk by name but records
-- nothing about what it dropped; section E replays this table.
--
-- What is at stake is the ON DELETE / ON UPDATE actions. schema.prisma
-- cannot express them and this file cannot see production's pg_constraint,
-- so a hardcoded `add constraint ... references ...` in section E silently
-- rewrites every fk to NO ACTION -- and legacy_id rollback restores keys,
-- not referential actions, so the loss is permanent. Reproduced on a
-- postgres:17 rebuild of the pre-migration schema: ON DELETE CASCADE on
-- product_views/product_reviews.product_id (which is the only reason
-- product.controller.js's deleteProduct can succeed today -- it deletes
-- order_items and the product, never the views or reviews), ON DELETE
-- CASCADE on products.store_id and order_items.order_id, ON DELETE SET
-- NULL on products.store_category_id and ON UPDATE CASCADE on
-- products.category_id were all downgraded to NO ACTION by the hardcoded
-- version, with no error, and deleting a viewed product then failed with
-- "violates foreign key constraint product_views_product_id_fkey".
--
-- `on commit drop`: this file is one transaction, so the snapshot is
-- cleaned up by the same commit that finishes the migration, and can never
-- survive to confuse a later run.
create temp table _uuid_v7_fk_snapshot on commit drop as
select
  c.conrelid                  as tbl_oid,
  c.conname::text             as conname,
  pg_get_constraintdef(c.oid) as condef,
  c.confdeltype               as confdeltype,
  c.confupdtype               as confupdtype,
  (select array_agg(a.attname::text order by k.ord)
     from unnest(c.conkey) with ordinality as k(attnum, ord)
     join pg_attribute a on a.attrelid = c.conrelid and a.attnum = k.attnum)
                              as child_cols
from pg_constraint c
where c.contype = 'f'
  and c.conrelid = any (array[
    'public.categories'::regclass, 'public.stores'::regclass,
    'public.products'::regclass, 'public.orders'::regclass,
    'public.order_items'::regclass, 'public.platform_settings'::regclass,
    'public.store_categories'::regclass, 'public.product_views'::regclass,
    'public.product_reviews'::regclass
  ]);

do $$
declare
  nine regclass[] := array[
    'public.categories'::regclass, 'public.stores'::regclass,
    'public.products'::regclass, 'public.orders'::regclass,
    'public.order_items'::regclass, 'public.platform_settings'::regclass,
    'public.store_categories'::regclass, 'public.product_views'::regclass,
    'public.product_reviews'::regclass
  ];
  v record;
  f record;
  pol record;
  idx record;
  trg record;
begin
  -- a) a view or matview that reads any of the nine tables silently
  --    starts reading legacy_id / legacy_*_id after section D's renames --
  --    no error, just permanently stale bigint-shaped output.
  for v in
    select distinct dependee.oid::regclass as obj, dependee.relkind
    from pg_depend
    join pg_rewrite  on pg_depend.objid = pg_rewrite.oid
    join pg_class as dependee  on pg_rewrite.ev_class = dependee.oid
    join pg_class as dependent on pg_depend.refobjid = dependent.oid
    where dependent.oid = any(nine)
      and dependee.oid <> dependent.oid  -- exclude the tables' own rewrite rules
      and dependee.relkind in ('v','m')
  loop
    raise exception 'pre-flight: % % depends on one of this migration''s nine tables -- after section D renames its columns, this object would silently start reading legacy_id/legacy_*_id instead of id, with no error',
      case v.relkind when 'm' then 'materialized view' else 'view' end, v.obj;
  end loop;

  -- b) a foreign key from a table OUTSIDE the nine into a table INSIDE the
  --    nine gets cascade-dropped by section C (which only knows to
  --    recreate the fks this migration is aware of) and never recreated.
  for f in
    select conrelid::regclass as child_table, conname
    from pg_constraint
    where contype = 'f'
      and confrelid = any(nine)
      and not (conrelid = any(nine))
  loop
    raise exception 'pre-flight: foreign key % on % references one of this migration''s nine tables from outside its scope -- section C would cascade-drop it and it would never be recreated',
      f.conname, f.child_table;
  end loop;

  -- c) a row-level security policy on any of the nine tables reads its
  --    USING/WITH CHECK expression against whatever column currently has
  --    that name -- it isn't rewritten by `rename column`. After section
  --    D, a policy written against `id` silently starts filtering on
  --    legacy_id (or, for the fk columns, legacy_*_id) instead. Not
  --    detectable after the fact from this file's comments alone -- the
  --    corruption is in the policy's stored expression, not anywhere this
  --    migration writes to.
  for pol in
    select polname, polrelid::regclass as tbl
    from pg_policy
    where polrelid = any(nine)
  loop
    raise exception 'pre-flight: policy % on % would silently repoint to legacy_id/legacy_*_id after section D''s renames, with no error',
      pol.polname, pol.tbl;
  end loop;

  -- d) section E now recreates only what the snapshot above captured. That
  --    is the point -- it preserves whatever production really has, under
  --    whatever name -- but it also means an fk that is MISSING from
  --    production would no longer be created by section E, where the old
  --    hardcoded version would have created it. Check the eight
  --    (table, column) pairs this migration knows about are all present, so
  --    that divergence is a loud stop here rather than a constraint that
  --    quietly ceases to exist. Matched by column, not by constraint name,
  --    so a differently-named fk in production is preserved rather than
  --    renamed.
  for f in
    select * from (values
      ('public.products'::regclass,         'category_id'),
      ('public.products'::regclass,         'store_id'),
      ('public.products'::regclass,         'store_category_id'),
      ('public.order_items'::regclass,      'order_id'),
      ('public.order_items'::regclass,      'product_id'),
      ('public.product_views'::regclass,    'product_id'),
      ('public.product_reviews'::regclass,  'product_id'),
      ('public.store_categories'::regclass, 'store_id')
    ) as expected(child_table, child_col)
    where not exists (
      select 1 from _uuid_v7_fk_snapshot s
      where s.tbl_oid = expected.child_table
        and expected.child_col = any(s.child_cols)
    )
  loop
    raise exception 'pre-flight: no foreign key on %.% -- section E recreates foreign keys from the section 0 snapshot, so this one would not exist after the migration either. Add it (or remove the pair from this check) before running.',
      f.child_table, f.child_col;
  end loop;

  -- e) a unique constraint, exclusion constraint or plain index whose
  --    columns include one section D renames follows the rename and
  --    silently repoints at the legacy_* column. For a unique constraint
  --    that is worse than "no longer enforced": rows written after this
  --    migration have legacy_* = null, nulls are distinct under a unique
  --    index, so a duplicate that used to be rejected now succeeds.
  --    Reproduced on postgres:17 -- UNIQUE (store_id, name) on
  --    store_categories became a unique index on (legacy_store_id, name),
  --    the migration committed with no error and no signal, and the same
  --    (store, name) pair then inserted twice.
  --
  --    The index arm goes through pg_depend rather than pg_index.indkey
  --    because indkey records 0 for an expression column and nothing at all
  --    for a WHERE predicate, so an index on (store_id::text), or a partial
  --    index with `where store_id is not null`, would be missed -- both of
  --    which repoint just as silently. pg_depend carries one row per column
  --    the index actually references, expressions and predicates included
  --    (verified empirically: both cases above show up there and neither
  --    shows up in indkey). Primary keys and constraint-backed indexes are
  --    not index-arm business -- section C drops and section E restores the
  --    pks, and unique/exclusion constraints are the constraint arm's job.
  for idx in
    with renamed(tbl, col) as (values
      ('public.categories'::regclass,        'id'),
      ('public.stores'::regclass,            'id'),
      ('public.products'::regclass,          'id'),
      ('public.products'::regclass,          'category_id'),
      ('public.products'::regclass,          'store_id'),
      ('public.products'::regclass,          'store_category_id'),
      ('public.orders'::regclass,            'id'),
      ('public.order_items'::regclass,       'id'),
      ('public.order_items'::regclass,       'order_id'),
      ('public.order_items'::regclass,       'product_id'),
      ('public.platform_settings'::regclass, 'id'),
      ('public.store_categories'::regclass,  'id'),
      ('public.store_categories'::regclass,  'store_id'),
      ('public.product_views'::regclass,     'product_id'),
      ('public.product_reviews'::regclass,   'product_id')
    )
    select case c.contype when 'u' then 'unique constraint' else 'exclusion constraint' end as kind,
           c.conname::text as objname, c.conrelid::regclass as tbl, r.col
    from pg_constraint c
    join renamed r      on r.tbl = c.conrelid
    join pg_attribute a on a.attrelid = c.conrelid and a.attname = r.col
    where c.contype in ('u','x')
      and a.attnum = any(c.conkey)
    union all
    select 'index', ci.relname::text, i.indrelid::regclass, r.col
    from pg_index i
    join pg_class ci    on ci.oid = i.indexrelid
    join renamed r      on r.tbl = i.indrelid
    join pg_attribute a on a.attrelid = i.indrelid and a.attname = r.col
    join pg_depend d    on d.classid    = 'pg_class'::regclass and d.objid    = i.indexrelid
                       and d.refclassid = 'pg_class'::regclass and d.refobjid = i.indrelid
                       and d.refobjsubid = a.attnum
    where not i.indisprimary
      and not exists (select 1 from pg_constraint c2 where c2.conindid = i.indexrelid)
  loop
    raise exception 'pre-flight: % % on % covers %.%, which section D renames to legacy_% -- it would follow the rename and silently start enforcing/indexing the legacy column instead (for a unique constraint that means duplicates it used to reject now succeed, because the legacy column is null on every new row). Drop it, run this migration, recreate it on the new column.',
      idx.kind, idx.objname, idx.tbl, idx.tbl, idx.col, idx.col;
  end loop;

  -- f) a trigger on any of the nine survives this migration untouched, but
  --    its function body was written against bigint ids. Anything that
  --    casts or stores an id as bigint -- an audit table with a bigint
  --    column is the obvious shape -- starts failing at the NEXT write,
  --    which is after this transaction commits, so nothing in the cutover
  --    checklist sees it: the migration passes, verify_integrity passes,
  --    and the first person to save a product gets the error. Reproduced on
  --    postgres:17 with an after-insert trigger writing new.id into a
  --    bigint audit column: the migration committed clean and the next
  --    insert raised 'column "product_id" is of type bigint but expression
  --    is of type uuid'.
  --
  --    tgisinternal = false excludes the triggers Postgres creates to
  --    enforce foreign keys, which section C drops and section E recreates
  --    correctly; those are not a hazard and would otherwise make this
  --    check fire on every run.
  for trg in
    select tgname, tgrelid::regclass as tbl
    from pg_trigger
    where tgrelid = any(nine)
      and tgisinternal = false
  loop
    raise exception 'pre-flight: trigger % on % survives this migration untouched, but its function was written when the ids were bigint -- if it casts, compares or stores an id, it breaks at the first write AFTER this transaction commits, where nothing in the cutover checklist would see it. Review it (and drop/recreate it around this migration) before running.',
      trg.tgname, trg.tbl;
  end loop;
end $$;

-- ---------------------------------------------------------------
-- A. new uuid primary keys on the seven bigint-keyed tables
-- ---------------------------------------------------------------
alter table public.categories        add column new_id uuid;
alter table public.stores            add column new_id uuid;
alter table public.products          add column new_id uuid;
alter table public.orders            add column new_id uuid;
alter table public.order_items       add column new_id uuid;
alter table public.platform_settings add column new_id uuid;
alter table public.store_categories  add column new_id uuid;

update public.categories        set new_id = public.uuid_generate_v7();
update public.stores            set new_id = public.uuid_generate_v7();
update public.products          set new_id = public.uuid_generate_v7();
update public.orders            set new_id = public.uuid_generate_v7();
update public.order_items       set new_id = public.uuid_generate_v7();
update public.platform_settings set new_id = public.uuid_generate_v7();
update public.store_categories  set new_id = public.uuid_generate_v7();

-- ---------------------------------------------------------------
-- B. new uuid foreign-key columns, populated by joining on the old ids
--    (this must run before section D renames anything -- old ids are
--    still in their original int columns here)
-- ---------------------------------------------------------------
alter table public.products          add column new_category_id       uuid;
alter table public.products          add column new_store_id          uuid;
alter table public.products          add column new_store_category_id uuid;
alter table public.order_items       add column new_order_id          uuid;
alter table public.order_items       add column new_product_id        uuid;
alter table public.product_views     add column new_product_id        uuid;
alter table public.product_reviews   add column new_product_id        uuid;
alter table public.store_categories  add column new_store_id          uuid;

update public.products p        set new_category_id       = c.new_id  from public.categories c        where p.category_id       = c.id;
update public.products p        set new_store_id          = s.new_id  from public.stores s            where p.store_id          = s.id;
update public.products p        set new_store_category_id = sc.new_id from public.store_categories sc where p.store_category_id = sc.id;
update public.order_items oi    set new_order_id          = o.new_id  from public.orders o            where oi.order_id         = o.id;
update public.order_items oi    set new_product_id        = p.new_id  from public.products p          where oi.product_id       = p.id;
update public.product_views pv  set new_product_id        = p.new_id  from public.products p          where pv.product_id       = p.id;
update public.product_reviews pr set new_product_id       = p.new_id  from public.products p          where pr.product_id       = p.id;
update public.store_categories sc set new_store_id        = s.new_id  from public.stores s            where sc.store_id         = s.id;

-- Guard: a non-null old FK that produced a null new FK means a pre-existing
-- orphan. Fail loudly, with the offending table named, rather than letting
-- section E's new FK constraints raise an opaque constraint violation.
-- Must run before section C touches any constraint.
do $$
declare bad int;
begin
  select count(*) into bad from public.products        where category_id       is not null and new_category_id       is null;
  if bad > 0 then raise exception 'products.category_id: % orphaned', bad; end if;
  select count(*) into bad from public.products        where store_id          is not null and new_store_id          is null;
  if bad > 0 then raise exception 'products.store_id: % orphaned', bad; end if;
  select count(*) into bad from public.products        where store_category_id is not null and new_store_category_id is null;
  if bad > 0 then raise exception 'products.store_category_id: % orphaned', bad; end if;
  select count(*) into bad from public.order_items     where order_id          is not null and new_order_id          is null;
  if bad > 0 then raise exception 'order_items.order_id: % orphaned', bad; end if;
  select count(*) into bad from public.order_items     where product_id        is not null and new_product_id        is null;
  if bad > 0 then raise exception 'order_items.product_id: % orphaned', bad; end if;
  select count(*) into bad from public.product_views   where product_id        is not null and new_product_id        is null;
  if bad > 0 then raise exception 'product_views.product_id: % orphaned', bad; end if;
  select count(*) into bad from public.product_reviews where product_id        is not null and new_product_id        is null;
  if bad > 0 then raise exception 'product_reviews.product_id: % orphaned', bad; end if;
  select count(*) into bad from public.store_categories where store_id         is not null and new_store_id          is null;
  if bad > 0 then raise exception 'store_categories.store_id: % orphaned', bad; end if;
end $$;

-- ---------------------------------------------------------------
-- C. drop old foreign-key and primary-key constraints
--    Names are discovered rather than assumed, because they were created
--    by Supabase's UI and by ad-hoc SQL over time.
--
--    The table set is matched by oid, via regclass literals cast from
--    explicit 'public.x' strings, not by comparing conrelid::regclass::text
--    against bare table names. That text form is search_path-dependent --
--    regclass renders schema-qualified whenever 'public' isn't resolvable
--    unqualified on the executing role's search_path -- so a text-based
--    membership test against bare names can silently match nothing
--    depending on who runs this. Reproduced empirically on postgres:17
--    (this project's version) with `set search_path to pg_catalog`: the
--    text-based version dropped zero constraints here, and the migration
--    then failed much later and misleadingly, at section E's `add primary
--    key`, with "multiple primary keys for table ...". Fails safe (full
--    rollback, no data touched) either way, but points at the wrong
--    section for whoever is debugging it under time pressure.
--
--    The `for r in select ...` cursor snapshots the full 'f'/'p' constraint
--    list once, before any drops happen. Every primary key in this set has
--    at least one foreign key elsewhere in the same set pointing at it
--    (e.g. stores_pkey <- products_store_id_fkey), and pg_constraint's scan
--    order here is whatever Postgres finds convenient -- not guaranteed to
--    put a table's own fk's ahead of a pk it references. Verified
--    empirically that the natural order puts stores/categories/etc.'s own
--    primary keys *before* other tables' foreign keys referencing them:
--    dropping such a pk with cascade drops the referencing fk immediately,
--    but that fk's row is still queued in this cursor -- so the loop later
--    tries to drop it a second time and Postgres raises "constraint ...
--    does not exist", aborting the whole transaction. The `if exists`
--    guard below re-checks each constraint immediately before dropping it
--    and skips anything an earlier iteration's cascade already removed.
--    Confirmed against a 9-table reproduction of this exact schema (all
--    fk's/pk's cleared, no error) before relying on it here.
--
--    contype is restricted to ('f','p') -- unique constraints (contype
--    'u'), such as stores_slug_key and stores_store_number_key, are never
--    selected by this loop, and (also verified empirically) do not depend
--    on a table's own primary key, so cascade does not remove them either;
--    see the guarded re-add in section E.
-- ---------------------------------------------------------------
do $$
declare
  r record;
  nine regclass[] := array[
    'public.categories'::regclass, 'public.stores'::regclass,
    'public.products'::regclass, 'public.orders'::regclass,
    'public.order_items'::regclass, 'public.platform_settings'::regclass,
    'public.store_categories'::regclass, 'public.product_views'::regclass,
    'public.product_reviews'::regclass
  ];
begin
  for r in
    select conrelid::regclass as tbl, conname
    from pg_constraint
    where contype in ('f','p')
      and conrelid = any(nine)
  loop
    if exists (select 1 from pg_constraint where conname = r.conname and conrelid = r.tbl::oid) then
      execute format('alter table %s drop constraint %I cascade', r.tbl, r.conname);
    end if;
  end loop;
end $$;

-- ---------------------------------------------------------------
-- D. swap columns: old -> legacy_*, new -> canonical
-- ---------------------------------------------------------------
alter table public.categories        rename column id to legacy_id;
alter table public.stores            rename column id to legacy_id;
alter table public.products          rename column id to legacy_id;
alter table public.orders            rename column id to legacy_id;
alter table public.order_items       rename column id to legacy_id;
alter table public.platform_settings rename column id to legacy_id;
alter table public.store_categories  rename column id to legacy_id;

alter table public.categories        rename column new_id to id;
alter table public.stores            rename column new_id to id;
alter table public.products          rename column new_id to id;
alter table public.orders            rename column new_id to id;
alter table public.order_items       rename column new_id to id;
alter table public.platform_settings rename column new_id to id;
alter table public.store_categories  rename column new_id to id;

alter table public.products         rename column category_id       to legacy_category_id;
alter table public.products         rename column store_id          to legacy_store_id;
alter table public.products         rename column store_category_id to legacy_store_category_id;
alter table public.order_items      rename column order_id          to legacy_order_id;
alter table public.order_items      rename column product_id        to legacy_product_id;
alter table public.product_views    rename column product_id        to legacy_product_id;
alter table public.product_reviews  rename column product_id        to legacy_product_id;
alter table public.store_categories rename column store_id          to legacy_store_id;

alter table public.products         rename column new_category_id       to category_id;
alter table public.products         rename column new_store_id          to store_id;
alter table public.products         rename column new_store_category_id to store_category_id;
alter table public.order_items      rename column new_order_id          to order_id;
alter table public.order_items      rename column new_product_id        to product_id;
alter table public.product_views    rename column new_product_id        to product_id;
alter table public.product_reviews  rename column new_product_id        to product_id;
alter table public.store_categories rename column new_store_id          to store_id;

-- ---------------------------------------------------------------
-- E. re-establish keys, defaults and constraints
-- ---------------------------------------------------------------
alter table public.categories        alter column id set not null, alter column id set default public.uuid_generate_v7(), add primary key (id);
alter table public.stores            alter column id set not null, alter column id set default public.uuid_generate_v7(), add primary key (id);
alter table public.products          alter column id set not null, alter column id set default public.uuid_generate_v7(), add primary key (id);
alter table public.orders            alter column id set not null, alter column id set default public.uuid_generate_v7(), add primary key (id);
alter table public.order_items       alter column id set not null, alter column id set default public.uuid_generate_v7(), add primary key (id);
alter table public.platform_settings alter column id set not null, alter column id set default public.uuid_generate_v7(), add primary key (id);
alter table public.store_categories  alter column id set not null, alter column id set default public.uuid_generate_v7(), add primary key (id);

-- product_views / product_reviews keep their existing uuid primary keys;
-- section C dropped them (their own pk, matched directly by that loop, not
-- via cascade), so restore.
alter table public.product_views   add primary key (id);
alter table public.product_reviews add primary key (id);

-- The foreign keys are re-added from section 0's snapshot -- name, columns,
-- referenced table and, critically, the ON DELETE / ON UPDATE actions
-- exactly as production had them. Nothing about them is hardcoded here.
--
-- Replaying pg_get_constraintdef's text across section D's renames is safe
-- because that text names COLUMNS, not types or attnums: a captured
-- "FOREIGN KEY (store_id) REFERENCES stores(id)" re-resolves against the
-- new uuid store_id / id, which by this point are the columns holding
-- those names. Verified empirically on postgres:17 against a rebuild of
-- the pre-migration schema, including under `set search_path to
-- pg_catalog` -- pg_get_constraintdef schema-qualifies the referenced
-- table itself when it has to, and the target table is rendered via
-- regclass, the same way section C renders it for the drop.
--
-- The `raise notice` is deliberate: a non-default referential action being
-- carried across is exactly the thing a human running the cutover should
-- see on their screen, because it is the thing that was silently lost
-- before and the thing legacy_id rollback cannot restore.
do $$
declare
  r record;
  acts text;
  code_name text[] := array['a','NO ACTION','r','RESTRICT','c','CASCADE','n','SET NULL','d','SET DEFAULT'];
  i int;
begin
  for r in select * from _uuid_v7_fk_snapshot order by tbl_oid::regclass::text, conname loop
    execute format('alter table %s add constraint %I %s', r.tbl_oid::regclass, r.conname, r.condef);

    if r.confdeltype <> 'a' or r.confupdtype <> 'a' then
      acts := '';
      for i in 1 .. array_length(code_name, 1) by 2 loop
        if r.confdeltype = code_name[i] and r.confdeltype <> 'a' then
          acts := acts || ' ON DELETE ' || code_name[i + 1];
        end if;
        if r.confupdtype = code_name[i] and r.confupdtype <> 'a' then
          acts := acts || ' ON UPDATE ' || code_name[i + 1];
        end if;
      end loop;
      raise notice 'section E: preserved non-default referential action on % (%):%',
        r.conname, r.tbl_oid::regclass, acts;
    end if;
  end loop;
end $$;

-- stores_slug_key / stores_store_number_key (contype 'u') are not touched
-- by section C's loop -- it only targets contype in ('f','p') -- and,
-- verified empirically against postgres:17, an unrelated unique constraint
-- on the same table does not cascade away when that table's primary key is
-- dropped (only dependent fks do). So these two almost certainly still
-- exist at this point, and an unconditional `add constraint ... unique`
-- here would raise "constraint already exists" and abort the whole
-- transaction.
--
-- The guard checks both pg_constraint AND pg_class (via to_regclass), not
-- pg_constraint alone: if slug/store_number uniqueness is enforced in
-- production by a bare UNIQUE INDEX named stores_slug_key with no backing
-- named constraint -- which schema.prisma's `@unique` cannot distinguish
-- from a real constraint -- pg_constraint finds nothing, this guard would
-- wrongly conclude it's safe to proceed, and `add constraint ... unique`
-- would itself fail while creating its backing index of that same name
-- ("relation ... already exists"), aborting the transaction. That is NOT
-- a harmless redundant index; it's the same abort this guard exists to
-- prevent, just from the other catalog. to_regclass checks pg_class
-- directly, which covers a relation of any kind under that name --
-- table, index, view -- so it catches this case too. Reproduced
-- empirically against postgres:17.
do $$
begin
  if not exists (
    select 1 from pg_constraint
    where conname = 'stores_slug_key' and conrelid = 'public.stores'::regclass
  ) and to_regclass('public.stores_slug_key') is null then
    alter table public.stores add constraint stores_slug_key unique (slug);
  end if;
  if not exists (
    select 1 from pg_constraint
    where conname = 'stores_store_number_key' and conrelid = 'public.stores'::regclass
  ) and to_regclass('public.stores_store_number_key') is null then
    alter table public.stores add constraint stores_store_number_key unique (store_number);
  end if;
end $$;

-- ---------------------------------------------------------------
-- F. seller ownership (security finding #0)
-- ---------------------------------------------------------------
alter table public.stores
  add column user_id uuid references auth.users(id) on delete set null;

-- A plain UNIQUE is correct here: Postgres treats NULLs as distinct, so
-- unlimited unowned stores are allowed. A partial index would add nothing
-- and Prisma cannot introspect one as @unique, which findUnique requires.
alter table public.stores add constraint stores_user_id_key unique (user_id);

-- Backfill: only doubly-unambiguous matches. This is the LAST use of the
-- email local-part heuristic; here it interprets history, never authorizes.
update public.stores s
set user_id = u.id
from auth.users u
where replace(replace(split_part(u.email, '@', 1), '+', ''), ' ', '') = s.phone
  and s.user_id is null
  and (select count(*) from auth.users u2
       where replace(replace(split_part(u2.email,'@',1),'+',''),' ','') = s.phone) = 1
  and (select count(*) from public.stores s2
       where s2.phone = replace(replace(split_part(u.email,'@',1),'+',''),' ','')) = 1;

-- ---------------------------------------------------------------
-- G. indexes on the new foreign keys
--
--    `if not exists`: pg_indexes lives in pg_catalog, which isn't exposed
--    over PostgREST, so there's no way to enumerate production's existing
--    index names with the access available for this task. This database
--    has been maintained through loose .sql files and ad-hoc scripts for a
--    long time, so a hand-made index already named e.g.
--    products_store_id_idx is plausible; without the guard, `create index`
--    would raise "already exists" and abort the whole transaction --
--    after every earlier section already succeeded, the worst place to
--    fail. Tradeoff, taken deliberately: if a same-named index already
--    exists, this silently keeps it instead of aborting -- and in the
--    realistic version of that scenario, the old index (built before
--    section D's renames) is now sitting on legacy_store_id, not
--    store_id, so the outcome is no index at all on the new uuid column,
--    not a differently-shaped index coexisting with it. A missing index
--    is a performance question to clean up later; an aborted migration
--    here is an outage.
-- ---------------------------------------------------------------
create index if not exists products_store_id_idx          on public.products(store_id);
create index if not exists products_category_id_idx       on public.products(category_id);
create index if not exists products_store_category_id_idx on public.products(store_category_id);
create index if not exists order_items_order_id_idx       on public.order_items(order_id);
create index if not exists order_items_product_id_idx     on public.order_items(product_id);
create index if not exists product_views_product_id_idx   on public.product_views(product_id);
create index if not exists product_reviews_product_id_idx on public.product_reviews(product_id);
create index if not exists store_categories_store_id_idx  on public.store_categories(store_id);

-- PostgREST caches its schema; every table here changed shape (columns
-- renamed, stores gained user_id). Without this, the API keeps serving the
-- pre-migration column set -- e.g. id as bigint -- until the cache reloads
-- on its own. NOTIFY delivery is deferred to commit by Postgres regardless
-- of where in the transaction it's issued, so placing it here keeps it
-- atomic with everything else: it never fires if this transaction rolls
-- back. Same rationale as 001_uuid_v7_function.sql.
notify pgrst, 'reload schema';

commit;
