-- Migrates categories, stores, products, orders, order_items,
-- platform_settings and store_categories from bigint primary keys to the
-- uuid v7 generated by public.uuid_generate_v7() (see
-- 001_uuid_v7_function.sql, which must run first). product_views and
-- product_reviews already have uuid primary keys and are not re-keyed --
-- they only have their FK to products repointed at the new uuid.
--
-- Also adds stores.user_id (uuid, references auth.users), closing the gap
-- where seller authorization is resolved by parsing the login email's
-- local part against stores.phone. Section F's backfill uses that same
-- heuristic one last time, to interpret history; after this migration it
-- never authorizes anything again.
--
-- legacy_id / legacy_*_id columns are kept deliberately -- not referenced
-- by anything, but they make rollback a key swap rather than a restore,
-- and 44 ad-hoc scripts at backend/ root still assume integer ids.
--
-- One transaction: any failure anywhere rolls back everything.
begin;

-- ---------------------------------------------------------------
-- A. new uuid primary keys on the seven bigint-keyed tables
-- ---------------------------------------------------------------
alter table public.categories        add column new_id uuid;
alter table public.stores            add column new_id uuid;
alter table public.products          add column new_id uuid;
alter table public.orders            add column new_id uuid;
alter table public.order_items       add column new_id uuid;
alter table public.platform_settings add column new_id uuid;
alter table public.store_categories  add column new_id uuid;

update public.categories        set new_id = public.uuid_generate_v7();
update public.stores            set new_id = public.uuid_generate_v7();
update public.products          set new_id = public.uuid_generate_v7();
update public.orders            set new_id = public.uuid_generate_v7();
update public.order_items       set new_id = public.uuid_generate_v7();
update public.platform_settings set new_id = public.uuid_generate_v7();
update public.store_categories  set new_id = public.uuid_generate_v7();

-- ---------------------------------------------------------------
-- B. new uuid foreign-key columns, populated by joining on the old ids
--    (this must run before section D renames anything -- old ids are
--    still in their original int columns here)
-- ---------------------------------------------------------------
alter table public.products          add column new_category_id       uuid;
alter table public.products          add column new_store_id          uuid;
alter table public.products          add column new_store_category_id uuid;
alter table public.order_items       add column new_order_id          uuid;
alter table public.order_items       add column new_product_id        uuid;
alter table public.product_views     add column new_product_id        uuid;
alter table public.product_reviews   add column new_product_id        uuid;
alter table public.store_categories  add column new_store_id          uuid;

update public.products p        set new_category_id       = c.new_id  from public.categories c        where p.category_id       = c.id;
update public.products p        set new_store_id          = s.new_id  from public.stores s            where p.store_id          = s.id;
update public.products p        set new_store_category_id = sc.new_id from public.store_categories sc where p.store_category_id = sc.id;
update public.order_items oi    set new_order_id          = o.new_id  from public.orders o            where oi.order_id         = o.id;
update public.order_items oi    set new_product_id        = p.new_id  from public.products p          where oi.product_id       = p.id;
update public.product_views pv  set new_product_id        = p.new_id  from public.products p          where pv.product_id       = p.id;
update public.product_reviews pr set new_product_id       = p.new_id  from public.products p          where pr.product_id       = p.id;
update public.store_categories sc set new_store_id        = s.new_id  from public.stores s            where sc.store_id         = s.id;

-- Guard: a non-null old FK that produced a null new FK means a pre-existing
-- orphan. Fail loudly, with the offending table named, rather than letting
-- section E's new FK constraints raise an opaque constraint violation.
-- Must run before section C touches any constraint.
do $$
declare bad int;
begin
  select count(*) into bad from public.products        where category_id       is not null and new_category_id       is null;
  if bad > 0 then raise exception 'products.category_id: % orphaned', bad; end if;
  select count(*) into bad from public.products        where store_id          is not null and new_store_id          is null;
  if bad > 0 then raise exception 'products.store_id: % orphaned', bad; end if;
  select count(*) into bad from public.products        where store_category_id is not null and new_store_category_id is null;
  if bad > 0 then raise exception 'products.store_category_id: % orphaned', bad; end if;
  select count(*) into bad from public.order_items     where order_id          is not null and new_order_id          is null;
  if bad > 0 then raise exception 'order_items.order_id: % orphaned', bad; end if;
  select count(*) into bad from public.order_items     where product_id        is not null and new_product_id        is null;
  if bad > 0 then raise exception 'order_items.product_id: % orphaned', bad; end if;
  select count(*) into bad from public.product_views   where product_id        is not null and new_product_id        is null;
  if bad > 0 then raise exception 'product_views.product_id: % orphaned', bad; end if;
  select count(*) into bad from public.product_reviews where product_id        is not null and new_product_id        is null;
  if bad > 0 then raise exception 'product_reviews.product_id: % orphaned', bad; end if;
  select count(*) into bad from public.store_categories where store_id         is not null and new_store_id          is null;
  if bad > 0 then raise exception 'store_categories.store_id: % orphaned', bad; end if;
end $$;

-- ---------------------------------------------------------------
-- C. drop old foreign-key and primary-key constraints
--    Names are discovered rather than assumed, because they were created
--    by Supabase's UI and by ad-hoc SQL over time. cascade is required
--    because this loop's iteration order is not guaranteed: if a table's
--    primary key is dropped before another table's foreign key that
--    references it, the fk would otherwise still be there depending on
--    that (now-gone) unique index. cascade lets that fk go with it instead
--    of erroring; it is caught explicitly by this same query on a later
--    iteration regardless, since every table with such an fk is also in
--    the list below. contype is restricted to ('f','p') -- unique
--    constraints (contype 'u'), such as stores_slug_key and
--    stores_store_number_key, are never selected by this loop and do not
--    depend on a table's own primary key, so cascade does not remove them
--    either; verified empirically against postgres:17 (this project's
--    version) before writing section E.
-- ---------------------------------------------------------------
do $$
declare r record;
begin
  for r in
    select conrelid::regclass as tbl, conname
    from pg_constraint
    where contype in ('f','p')
      and connamespace = 'public'::regnamespace
      and conrelid::regclass::text in
        ('categories','stores','products','orders','order_items',
         'platform_settings','store_categories','product_views','product_reviews')
  loop
    execute format('alter table %s drop constraint %I cascade', r.tbl, r.conname);
  end loop;
end $$;

-- ---------------------------------------------------------------
-- D. swap columns: old -> legacy_*, new -> canonical
-- ---------------------------------------------------------------
alter table public.categories        rename column id to legacy_id;
alter table public.stores            rename column id to legacy_id;
alter table public.products          rename column id to legacy_id;
alter table public.orders            rename column id to legacy_id;
alter table public.order_items       rename column id to legacy_id;
alter table public.platform_settings rename column id to legacy_id;
alter table public.store_categories  rename column id to legacy_id;

alter table public.categories        rename column new_id to id;
alter table public.stores            rename column new_id to id;
alter table public.products          rename column new_id to id;
alter table public.orders            rename column new_id to id;
alter table public.order_items       rename column new_id to id;
alter table public.platform_settings rename column new_id to id;
alter table public.store_categories  rename column new_id to id;

alter table public.products         rename column category_id       to legacy_category_id;
alter table public.products         rename column store_id          to legacy_store_id;
alter table public.products         rename column store_category_id to legacy_store_category_id;
alter table public.order_items      rename column order_id          to legacy_order_id;
alter table public.order_items      rename column product_id        to legacy_product_id;
alter table public.product_views    rename column product_id        to legacy_product_id;
alter table public.product_reviews  rename column product_id        to legacy_product_id;
alter table public.store_categories rename column store_id          to legacy_store_id;

alter table public.products         rename column new_category_id       to category_id;
alter table public.products         rename column new_store_id          to store_id;
alter table public.products         rename column new_store_category_id to store_category_id;
alter table public.order_items      rename column new_order_id          to order_id;
alter table public.order_items      rename column new_product_id        to product_id;
alter table public.product_views    rename column new_product_id        to product_id;
alter table public.product_reviews  rename column new_product_id        to product_id;
alter table public.store_categories rename column new_store_id          to store_id;

-- ---------------------------------------------------------------
-- E. re-establish keys, defaults and constraints
-- ---------------------------------------------------------------
alter table public.categories        alter column id set not null, alter column id set default public.uuid_generate_v7(), add primary key (id);
alter table public.stores            alter column id set not null, alter column id set default public.uuid_generate_v7(), add primary key (id);
alter table public.products          alter column id set not null, alter column id set default public.uuid_generate_v7(), add primary key (id);
alter table public.orders            alter column id set not null, alter column id set default public.uuid_generate_v7(), add primary key (id);
alter table public.order_items       alter column id set not null, alter column id set default public.uuid_generate_v7(), add primary key (id);
alter table public.platform_settings alter column id set not null, alter column id set default public.uuid_generate_v7(), add primary key (id);
alter table public.store_categories  alter column id set not null, alter column id set default public.uuid_generate_v7(), add primary key (id);

-- product_views / product_reviews keep their existing uuid primary keys;
-- section C dropped them (their own pk, matched directly by that loop, not
-- via cascade), so restore.
alter table public.product_views   add primary key (id);
alter table public.product_reviews add primary key (id);

alter table public.products         add constraint products_category_id_fkey       foreign key (category_id)       references public.categories(id);
alter table public.products         add constraint products_store_id_fkey          foreign key (store_id)          references public.stores(id);
alter table public.products         add constraint products_store_category_id_fkey foreign key (store_category_id) references public.store_categories(id);
alter table public.order_items      add constraint order_items_order_id_fkey       foreign key (order_id)          references public.orders(id);
alter table public.order_items      add constraint order_items_product_id_fkey     foreign key (product_id)        references public.products(id);
alter table public.product_views    add constraint product_views_product_id_fkey   foreign key (product_id)        references public.products(id);
alter table public.product_reviews  add constraint product_reviews_product_id_fkey foreign key (product_id)        references public.products(id);
alter table public.store_categories add constraint store_categories_store_id_fkey  foreign key (store_id)          references public.stores(id);

-- stores_slug_key / stores_store_number_key (contype 'u') are not touched
-- by section C's loop -- it only targets contype in ('f','p') -- and,
-- verified empirically against postgres:17, an unrelated unique constraint
-- on the same table does not cascade away when that table's primary key is
-- dropped (only dependent fks do). So these two almost certainly still
-- exist at this point, and an unconditional `add constraint ... unique`
-- here would raise "constraint already exists" and abort the whole
-- transaction. Guarded so this statement is correct either way: it backs
-- up the assumption that they were dropped without depending on it.
do $$
begin
  if not exists (
    select 1 from pg_constraint
    where conname = 'stores_slug_key' and conrelid = 'public.stores'::regclass
  ) then
    alter table public.stores add constraint stores_slug_key unique (slug);
  end if;
  if not exists (
    select 1 from pg_constraint
    where conname = 'stores_store_number_key' and conrelid = 'public.stores'::regclass
  ) then
    alter table public.stores add constraint stores_store_number_key unique (store_number);
  end if;
end $$;

-- ---------------------------------------------------------------
-- F. seller ownership (security finding #0)
-- ---------------------------------------------------------------
alter table public.stores
  add column user_id uuid references auth.users(id) on delete set null;

-- A plain UNIQUE is correct here: Postgres treats NULLs as distinct, so
-- unlimited unowned stores are allowed. A partial index would add nothing
-- and Prisma cannot introspect one as @unique, which findUnique requires.
alter table public.stores add constraint stores_user_id_key unique (user_id);

-- Backfill: only doubly-unambiguous matches. This is the LAST use of the
-- email local-part heuristic; here it interprets history, never authorizes.
update public.stores s
set user_id = u.id
from auth.users u
where replace(replace(split_part(u.email, '@', 1), '+', ''), ' ', '') = s.phone
  and s.user_id is null
  and (select count(*) from auth.users u2
       where replace(replace(split_part(u2.email,'@',1),'+',''),' ','') = s.phone) = 1
  and (select count(*) from public.stores s2
       where s2.phone = replace(replace(split_part(u.email,'@',1),'+',''),' ','')) = 1;

-- ---------------------------------------------------------------
-- G. indexes on the new foreign keys
-- ---------------------------------------------------------------
create index products_store_id_idx          on public.products(store_id);
create index products_category_id_idx       on public.products(category_id);
create index products_store_category_id_idx on public.products(store_category_id);
create index order_items_order_id_idx       on public.order_items(order_id);
create index order_items_product_id_idx     on public.order_items(product_id);
create index product_views_product_id_idx   on public.product_views(product_id);
create index product_reviews_product_id_idx on public.product_reviews(product_id);
create index store_categories_store_id_idx  on public.store_categories(store_id);

-- PostgREST caches its schema; every table here changed shape (columns
-- renamed, stores gained user_id). Without this, the API keeps serving the
-- pre-migration column set -- e.g. id as bigint -- until the cache reloads
-- on its own. NOTIFY delivery is deferred to commit by Postgres regardless
-- of where in the transaction it's issued, so placing it here keeps it
-- atomic with everything else: it never fires if this transaction rolls
-- back. Same rationale as 001_uuid_v7_function.sql.
notify pgrst, 'reload schema';

commit;
